export const GET_USERS_REQUESTED= "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS= "GET_USERS_SUCCESS";
export const GET_USERS_FAILED= "GET_USERS_FAILED";
export const GET_NEWS_REQUESTED= "GET_NEWS_REQUESTED";
export const GET_NEWS_SUCCESS= "GET_NEWS_SUCCESS";
export const GET_NEWS_FAILED= "GET_NEWS_FAILED";